version: '3'
services:
  web:
    build: 
      # overriding dockerfile selection
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
      # override command over dockerfile
    command: ["npm", "run", "test"]